🤼 Sumô Controller 🤖
ps-thunderatz/sumo_controller pull request #16
Opened 2021-09-06 03:21 UTC by GabrielCosme

Finalização do pacote sumô_controller.

2021-09-06 03:29 UTC, LucasHaug commented on README.md
> +Dica: O robô possui 3 sensores de distânica, então se quiser aproveitar o máximo das informações disponíveis, você precisará criar mais de um objeto `DistanceSensor`.
```suggestion
Dica: O robô possui 3 sensores de distância, então se quiser aproveitar o máximo das informações disponíveis, você precisará criar mais de um objeto `DistanceSensor`.
```

2021-09-06 03:29 UTC, LucasHaug commented on src/utils/line_sensor.py
> +        threshold = (white_line - black_line) / 3
~~eu vou só aceitar esse 3~~

2021-09-06 03:40 UTC, GabrielCosme commented on src/utils/line_sensor.py
> +        threshold = (white_line - black_line) / 3
Kkkkkk eh q ai a histerese fica em um terço e dois terços

2021-09-06 04:00 UTC, LucasHaug approved these changes

2021-09-07 19:41 UTC, lucastrschneider requested changes
Tem que padronizar as docstrings, na classe e nos arquivos está tudo em ingles, enquanto nos métodos foi tudo pra port. Tirando isso, parece bem bom.

Aquele link do README precisa testar pq não sei se é aquilo mesmo, mas não sei se tem como testar sem dar push e ver no github, no meu local eu testei e nenhum link funciona, então acho que não :p

Uma coisa que eu pensei e que talvez seja legal é uma seção entre "arquivos do projeto" e "como executar" que liste os launchfiles, os argumentos que eles podem receber, valores padrões, e uma pequena descrição de cada um. Isso vai ser muito importante no sumo_simulation, mas se pa melhor fazer aqui tbm para padronizar

2021-09-07 19:41 UTC, lucastrschneider commented on README.md
> +  - [⚖️ IMU](#-imu)
```suggestion
  - [⚖️ IMU](#%EF%B8%8F-imu)
```

O link não tava funcionando comigo, não sei se ta certo assim, mas da pra ver se funciona, era assim que aparecia no meu navegador quando eu clicava nessa seção pelo menos

2021-09-07 19:41 UTC, lucastrschneider commented on package.xml
> +
```suggestion
  <depend>rospy</depend>
  <depend>roslaunch</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>

```

2021-09-07 19:41 UTC, lucastrschneider commented on src/utils/distance_sensor.py
> +    """Class to hanlde a distance sensor"""
```suggestion
    """Class to handle a distance sensor"""
```

2021-09-07 19:41 UTC, lucastrschneider commented on src/utils/distance_sensor.py
> +    """Class to hanlde a distance sensor"""
Eseria melhor mudar pra port que nem o resto da documentação né?

2021-09-07 19:41 UTC, lucastrschneider commented on src/utils/distance_sensor.py
> +    """Class to hanlde a distance sensor"""
~ou mudar toda a documentação pra ingles tbm~

2021-09-07 20:12 UTC, lucastrschneider commented on README.md
> +roslaunch sumo_controller sumo_controller.launch team:=red
Eu to muito confuso agora, a gnt pode passar o red sem aspas? pq é uma string né, mas não sei mais qual o certo agora

O mesmo vale pro strategy la embaixo

2021-09-08 15:21 UTC, lucastrschneider commented on README.md
> +roslaunch sumo_controller sumo_controller.launch team:=red
Então é isso kkkkk

2021-09-08 21:12 UTC, mariarezende07 approved these changes

2021-09-08 22:09 UTC, LucasHaug commented on src/example_node.py
> +"""Simples node de exemplo para realização de testes
```suggestion
"""Node simples de exemplo para realização de testes
```

2021-09-08 22:52 UTC, GabrielCosme commented on src/example_node.py
> +"""Simples node de exemplo para realização de testes
Eh q n eh um node simples, eh um node de exempĺo simples kkkkkkk. Ai bota antes pse referir a td sem parecer que o exemplo é simples

2021-09-08 22:57 UTC, LucasHaug commented on src/example_node.py
> +"""Simples node de exemplo para realização de testes
Pronto editei a sugestão huashuashuashuhussa

2021-09-08 23:11 UTC, LucasHaug commented on src/example_node.py
> +"""Simples node de exemplo para realização de testes
Votado:

https://doodle.com/poll/9q9n2scywbr8ita5?utm_source=poll&utm_medium=link

2021-09-08 23:22 UTC, merged

2021-09-08 23:52 UTC, LucasHaug approved these changes